swagger: "2.0"
info:
  description: '<font size="2" color="red">MIT License</font>'
  version: "1.0.3"
  title: "Distance-Between"
  license:
    name: "Erlan Lucio"
    url: "https://github.com/luciierlan"
host: "localhost:5000"
basePath: "/api"
tags:
  - name: "ROUTES"
    description: "<br><br>"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /search?origem=-43.9353,-19.9245&destino=-46.6333,-23.5505:
    get:
      tags:
        - "ROUTES"
      summary: "(OSRM) Calculate Distance, Latitude and Longitude!"
      description:
        "Origem Belo Horizonte (-43.9353,-19.9245) </br>
         Destino São Paulo (-46.6333,-23.5505) </br>
         http://localhost:5000/api/search?origem=-43.9353,-19.9245&destino=-46.6333,-23.5505"
      parameters: []
      responses:
        200:
          description: "Success"
        500:
          description: "Error"
      x-swagger-router-controller: "ROUTES"
