openapi: 3.0.0
info:
  description: '<font size="2" color="red">MIT License</font>'
  title: "Distance-Between"
  contact:
    name: Erlan Lucio
    url: https://github.com/lucioerlan
  version: '1.0'
servers:
- url: https://distance-between.herokuapp.com/api
  variables: {}
paths:
  /search/reverse:
    get:
      tags:
      - ROUTES
      summary: LAT E LON
      operationId: LATELON
      parameters:
      - name: OriginOne
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: lat=-9.8309656
      - name: OriginTwo
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: lon=-67.9520886
      - name: DestOne
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: lat=-3.1316333
      - name: DestTwo
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: lon=-59.9825041
      - name: method
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: reverse
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /search/geo:
    get:
      tags:
      - ROUTES
      summary: ADDRESS
      operationId: ADDRESS
      parameters:
      - name: OriginOne
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: city=Bujari
      - name: OriginTwo
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: state=AC
      - name: DestOne
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: city=Manaus
      - name: DestTwo
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: state=AM
      - name: method
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: search
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
tags:
- name: ROUTES
